# Generated by scripts/generate_homebrew_core_formula.sh for v0.1.1
# Regenerate this formula for every release tag.
class Docwarp < Formula
  desc "Bidirectional Markdown <-> DOCX converter"
  homepage "https://github.com/N10ELabs/docwarp"
  url "https://github.com/N10ELabs/docwarp/archive/refs/tags/v0.1.1.tar.gz"
  sha256 "9754880a2e4ab4d929fbdbf2c1188d9585354d4e6a0e6e13aeabf8202b6a6d4c"
  license "Apache-2.0"

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args(path: "crates/docwarp-cli")
  end

  test do
    assert_match "Convert documentation", shell_output("#{bin}/docwarp --help")
  end
end
