#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 4 || $# -gt 5 ]]; then
  echo "usage: $0 <owner> <repo> <tag> <output_path> [sha256]" >&2
  echo "example: $0 N10ELabs docwarp v0.1.0 packaging/homebrew-core/docwarp.rb" >&2
  exit 1
fi

owner="$1"
repo="$2"
tag="$3"
output_path="$4"
sha_override="${5:-}"

if [[ "${tag}" != v* ]]; then
  echo "tag must start with v (for example: v0.1.0)" >&2
  exit 1
fi

archive_url="https://github.com/${owner}/${repo}/archive/refs/tags/${tag}.tar.gz"

if [[ -n "${sha_override}" ]]; then
  archive_sha="${sha_override}"
else
  if ! archive_sha="$(curl -fsSL "${archive_url}" | shasum -a 256 | awk '{print $1}')"; then
    echo "failed to download ${archive_url}" >&2
    echo "if the repository is private, make it public first or pass sha256 explicitly." >&2
    exit 1
  fi
fi

mkdir -p "$(dirname "${output_path}")"

cat >"${output_path}" <<EOF
# Generated by scripts/generate_homebrew_core_formula.sh for ${tag}
# Regenerate this formula for every release tag.
class Docwarp < Formula
  desc "Bidirectional Markdown <-> DOCX converter"
  homepage "https://github.com/${owner}/${repo}"
  url "${archive_url}"
  sha256 "${archive_sha}"
  license "Apache-2.0"

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args(path: "crates/docwarp-cli")
  end

  test do
    assert_match "Convert documentation", shell_output("#{bin}/docwarp --help")
  end
end
EOF

echo "wrote core-candidate formula to ${output_path}"
echo "source url: ${archive_url}"
echo "sha256: ${archive_sha}"
